### ISSUE TITLE
Bike Station Duplication in DB

### ISSUE THREAD

**Issue by axiao01** [AdamWu-330/Pub-Sub-System#5]
Frontend assumes Bike Station to be unique (so only ~ 600 to 700 bike station documents are present in db, each with a unique ID), while backend stores bike station like other fields. This caused the bike preview to not behave as expectedly on frontend. Is it possible when pulling new data, we can check for duplicacy of station ID and only keep the newest bike station status, deleting all the old ones? (Concept is more like cameraCurrent, only the newest status of each bikeStation is kept so that there is no duplicate bikeStation ID in the collection).
Sorry for the late notice, I didn't test the bike preview part since the demo.

**Comment by AdamWu-330** [comment]
done
